openapi: 3.0.0
info:
  title: Documentation de l'API
  version: 1.0.0
  description: Documentation des points d'accès de l'API
servers:
  - url: http://localhost:3000
    description: Serveur local
tags:
  - name: Utilisateur
    description: API pour la gestion des utilisateurs
  - name: Conversation
    description: API pour la gestion des conversations
  - name: Message
    description: API pour la gestion des messages
  - name: Plante
    description: API pour la gestion des plantes
  - name: Image
    description: API pour la gestion des images
  - name: Conseil
    description: API pour la gestion des conseils

paths:
  /ajouter:
    post:
      summary: Ajouter un nouvel utilisateur
      tags: 
        - Utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom_utl:
                  type: string
                  description: Nom de l'utilisateur
                pre_utl:
                  type: string
                  description: Prénom de l'utilisateur
                age_utl:
                  type: integer
                  description: Âge de l'utilisateur
                num_utl:
                  type: string
                  description: Numéro de téléphone de l'utilisateur
                eml_utl:
                  type: string
                  description: Adresse email de l'utilisateur
                adr_utl:
                  type: string
                  description: Adresse de l'utilisateur
                psd_utl:
                  type: string
                  description: Pseudonyme de l'utilisateur
                mdp_utl:
                  type: string
                  description: Mot de passe de l'utilisateur
              required:
                - nom_utl
                - pre_utl
                - age_utl
                - num_utl
                - eml_utl
                - adr_utl
                - psd_utl
                - mdp_utl
      responses:
        '200':
          description: Utilisateur ajouté avec succès
        '400':
          description: Tous les champs sont requis
        '500':
          description: Erreur lors de l'ajout de l'utilisateur

  /verifier:
    post:
      summary: Vérifier les informations d'utilisateur
      tags: 
        - Utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                psd_utl:
                  type: string
                  description: Pseudonyme de l'utilisateur
                mdp_utl:
                  type: string
                  description: Mot de passe de l'utilisateur
              required:
                - psd_utl
                - mdp_utl
      responses:
        '200':
          description: Utilisateur vérifié avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Jeton d'authentification
        '400':
          description: Le nom d'utilisateur et le mot de passe sont requis
        '401':
          description: Informations d'identification incorrectes
        '500':
          description: Erreur lors de la vérification de l'utilisateur

  /supprimer:
    delete:
      summary: Supprimer un utilisateur
      tags: 
        - Utilisateur
      parameters:
        - in: query
          name: psd_utl
          required: true
          schema:
            type: string
          description: Pseudonyme de l'utilisateur à supprimer
      responses:
        '200':
          description: Utilisateur supprimé avec succès
        '400':
          description: Le nom d'utilisateur est requis
        '500':
          description: Erreur lors de la suppression de l'utilisateur

  /pseudo:
    get:
      summary: Obtenir le pseudonyme de l'utilisateur
      tags: 
        - Utilisateur
      parameters:
        - in: query
          name: id_utl
          required: true
          schema:
            type: integer
          description: ID de l'utilisateur
      responses:
        '200':
          description: Pseudonyme de l'utilisateur récupéré avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  utilisateur:
                    type: object
                    properties:
                      id_utl:
                        type: integer
                        description: ID de l'utilisateur
                      pseudo:
                        type: string
                        description: Pseudonyme de l'utilisateur
        '400':
          description: L'ID de l'utilisateur est requis
        '500':
          description: Erreur lors de la récupération du pseudonyme de l'utilisateur

  /conversation/ajouter:
    post:
      summary: Ajouter une nouvelle conversation
      tags: 
        - Conversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_plt:
                  type: integer
                  description: ID de la plateforme
                id_utl1:
                  type: integer
                  description: ID du premier utilisateur
                id_utl2:
                  type: integer
                  description: ID du second utilisateur
                type:
                  type: string
                  description: Type de la conversation
              required:
                - id_plt
                - id_utl1
                - id_utl2
                - type
      responses:
        '200':
          description: Conversation ajoutée avec succès
        '500':
          description: Erreur lors de l'ajout de la conversation

  /message/ajouter:
    post:
      summary: Ajouter un nouveau message
      tags: 
        - Message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_conv:
                  type: integer
                  description: ID de la conversation
                dat_msg:
                  type: string
                  format: date-time
                  description: Date et heure du message
                txt_msg:
                  type: string
                  description: Texte du message
                id_sender:
                  type: integer
                  description: ID de l'expéditeur
              required:
                - id_conv
                - dat_msg
                - txt_msg
                - id_sender
      responses:
        '200':
          description: Message ajouté avec succès
        '500':
          description: Erreur lors de l'ajout du message

  /message:
    get:
      summary: Obtenir les messages par ID de conversation
      tags: 
        - Message
      parameters:
        - in: query
          name: id_conv
          required: true
          schema:
            type: integer
          description: ID de la conversation
      responses:
        '200':
          description: Messages récupérés avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_msg:
                      type: integer
                      description: ID du message
                    id_conv:
                      type: integer
                      description: ID de la conversation
                    dat_msg:
                      type: string
                      format: date-time
                      description: Date et heure du message
                    txt_msg:
                      type: string
                      description: Texte du message
                    id_sender:
                      type: integer
                      description: ID de l'expéditeur
        '500':
          description: Erreur lors de la récupération des messages

  /plante/afficher:
    get:
      summary: Afficher une plante
      tags: 
        - Plante
      parameters:
        - in: query
          name: adr_plt
          required: true
          schema:
            type: string
          description: Adresse de la plante
      responses:
        '200':
          description: Plante récupérée avec succès
        '500':
          description: Erreur lors de la récupération de la plante

  /plante/afficherTout:
    get:
      summary: Afficher toutes les plantes
      tags: 
        - Plante
      responses:
        '200':
          description: Plantes récupérées avec succès
        '500':
          description: Erreur lors de la récupération des plantes

  /plante/afficherGardees:
    get:
      summary: Afficher les plantes gardées par un utilisateur
      tags: 
        - Plante
      parameters:
        - in: query
          name: psd_utl
          required: true
          schema:
            type: string
          description: Pseudonyme de l'utilisateur
      responses:
        '200':
          description: Plantes gardées récupérées avec succès
        '500':
          description: Erreur lors de la récupération des plantes gardées

  /plante/afficherFaitesGardees:
    get:
      summary: Afficher les plantes faites gardées par un utilisateur
      tags: 
        - Plante
      parameters:
        - in: query
          name: psd_utl
          required: true
          schema:
            type: string
          description: Pseudonyme de l'utilisateur
      responses:
        '200':
          description: Plantes faites gardées récupérées avec succès
        '500':
          description: Erreur lors de la récupération des plantes faites gardées

  /plante/recupererlocalisation:
    get:
      summary: Récupérer la localisation de la plante
      tags: 
        - Plante
      responses:
        '200':
          description: Localisation de la plante récupérée avec succès
        '500':
          description: Erreur lors de la récupération de la localisation de la plante

  /plante/ajouter:
    post:
      summary: Ajouter une nouvelle plante
      tags: 
        - Plante
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                esp_plt:
                  type: string
                  description: Espèce de la plante
                des_plt:
                  type: string
                  description: Description de la plante
                nom_plt:
                  type: string
                  description: Nom de la plante
                adr_plt:
                  type: string
                  description: Adresse de la plante
                dat_deb_plt:
                  type: string
                  format: date
                  description: Date de début de la plante
                dat_fin_plt:
                  type: string
                  format: date
                  description: Date de fin de la plante
                id_proprietaire:
                  type: integer
                  description: ID du propriétaire de la plante
              required:
                - esp_plt
                - des_plt
                - nom_plt
                - adr_plt
                - dat_deb_plt
                - dat_fin_plt
                - id_proprietaire
      responses:
        '200':
          description: Plante ajoutée avec succès
        '500':
          description: Erreur lors de l'ajout de la plante

  /plante/ajouterGardien:
    patch:
      summary: Ajouter un gardien pour une plante
      tags: 
        - Plante
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_plt:
                  type: integer
                  description: ID de la plante
                id_utl:
                  type: integer
                  description: ID de l'utilisateur
              required:
                - id_plt
                - id_utl
      responses:
        '200':
          description: Gardien ajouté avec succès
        '500':
          description: Erreur lors de l'ajout du gardien

  /conversation/afficher:
    get:
      summary: Afficher les conversations d'un utilisateur
      tags: 
        - Conversation
      parameters:
        - in: query
          name: id_utl
          required: true
          schema:
            type: integer
          description: ID de l'utilisateur
      responses:
        '200':
          description: Conversations récupérées avec succès
        '500':
          description: Erreur lors de la récupération des conversations

  /image/afficher:
    get:
      summary: Afficher une image
      tags: 
        - Image
      parameters:
        - in: query
          name: id_img
          required: true
          schema:
            type: integer
          description: ID de l'image
      responses:
        '200':
          description: Image récupérée avec succès
        '500':
          description: Erreur lors de la récupération de l'image

  /image/afficher_tous:
    get:
      summary: Afficher toutes les images d'un utilisateur ou d'une plante
      tags: 
        - Image
      parameters:
        - in: query
          name: id_utl
          schema:
            type: integer
          description: ID de l'utilisateur
        - in: query
          name: id_utl_1
          schema:
            type: integer
          description: ID du second utilisateur
        - in: query
          name: id_plt
          schema:
            type: integer
          description: ID de la plante
      responses:
        '200':
          description: Images récupérées avec succès
        '500':
          description: Erreur lors de la récupération des images

  /image/ajouter:
    post:
      summary: Ajouter une nouvelle image
      tags: 
        - Image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url_img:
                  type: string
                  description: URL de l'image
                id_utl:
                  type: integer
                  description: ID de l'utilisateur
                id_utl_1:
                  type: integer
                  description: ID du second utilisateur
                id_plt:
                  type: integer
                  description: ID de la plante
              required:
                - url_img
                - id_utl
                - id_utl_1
                - id_plt
      responses:
        '200':
          description: Image ajoutée avec succès
        '500':
          description: Erreur lors de l'ajout de l'image

  /conseil/ajouter:
    post:
      summary: Ajouter un nouveau conseil
      tags: 
        - Conseil
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dsc_csn:
                  type: string
                  description: Description du conseil
                id_plt:
                  type: integer
                  description: ID de la plante
                psd_utl:
                  type: string
                  description: Pseudonyme de l'utilisateur
              required:
                - dsc_csn
                - id_plt
                - psd_utl
      responses:
        '200':
          description: Conseil ajouté avec succès
        '500':
          description: Erreur lors de l'ajout du conseil

  /conseil/afficher:
    get:
      summary: Afficher un conseil
      tags: 
        - Conseil
      parameters:
        - in: query
          name: id_cns
          required: true
          schema:
            type: integer
          description: ID du conseil
      responses:
        '200':
          description: Conseil récupéré avec succès
        '500':
          description: Erreur lors de la récupération du conseil
