openapi: 3.0.0
info:
  title: Documentation de l'API
  version: 1.0.0
  description: Documentation des points d'accès de l'API
servers:
  - url: http://localhost:3000
    description: Serveur local
tags:
  - name: Utilisateur
    description: API pour la gestion des utilisateurs
  - name: Conversation
    description: API pour la gestion des conversations
  - name: Message
    description: API pour la gestion des messages

paths:
  /ajouter:
    post:
      summary: Ajouter un nouvel utilisateur
      tags: 
        - Utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom_utl:
                  type: string
                pre_ult:
                  type: string
                age_utl:
                  type: integer
                num_utl:
                  type: string
                eml_utl:
                  type: string
                adr_utl:
                  type: string
                psd_utl:
                  type: string
                mdp_utl:
                  type: string
              required:
                - nom_utl
                - pre_ult
                - age_utl
                - num_utl
                - eml_utl
                - adr_utl
                - psd_utl
                - mdp_utl
      responses:
        '200':
          description: Utilisateur ajouté avec succès
        '400':
          description: Tous les champs sont requis
        '500':
          description: Erreur lors de l'ajout de l'utilisateur

  /verifier:
    post:
      summary: Vérifier les informations d'utilisateur
      tags: 
        - Utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                psd_utl:
                  type: string
                mdp_utl:
                  type: string
              required:
                - psd_utl
                - mdp_utl
      responses:
        '200':
          description: Utilisateur vérifié avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Le nom d'utilisateur et le mot de passe sont requis
        '401':
          description: Informations d'identification incorrectes
        '500':
          description: Erreur lors de la vérification de l'utilisateur

  /supprimer:
    delete:
      summary: Supprimer un utilisateur
      tags: 
        - Utilisateur
      parameters:
        - in: query
          name: psd_utl
          required: true
          schema:
            type: string
          description: Nom d'utilisateur de l'utilisateur à supprimer
      responses:
        '200':
          description: Utilisateur supprimé avec succès
        '400':
          description: Le nom d'utilisateur est requis
        '500':
          description: Erreur lors de la suppression de l'utilisateur

  /pseudo:
    get:
      summary: Obtenir le pseudonyme de l'utilisateur
      tags: 
        - Utilisateur
      parameters:
        - in: query
          name: id_utl
          required: true
          schema:
            type: integer
          description: ID de l'utilisateur
      responses:
        '200':
          description: Pseudonyme de l'utilisateur récupéré avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  utilisateur:
                    type: object
                    properties:
                      id_utl:
                        type: integer
                      pseudo:
                        type: string
        '400':
          description: L'ID de l'utilisateur est requis
        '500':
          description: Erreur lors de la récupération du pseudonyme de l'utilisateur

  /conversation/ajouter:
    post:
      summary: Ajouter une nouvelle conversation
      tags: 
        - Conversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_plt:
                  type: integer
                id_utl1:
                  type: integer
                id_utl2:
                  type: integer
                type:
                  type: string
              required:
                - id_plt
                - id_utl1
                - id_utl2
                - type
      responses:
        '200':
          description: Conversation ajoutée avec succès
        '500':
          description: Erreur lors de l'ajout de la conversation

  /message/ajouter:
    post:
      summary: Ajouter un nouveau message
      tags: 
        - Message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_conv:
                  type: integer
                dat_msg:
                  type: string
                  format: date-time
                txt_msg:
                  type: string
                id_sender:
                  type: integer
              required:
                - id_conv
                - dat_msg
                - txt_msg
                - id_sender
      responses:
        '200':
          description: Message ajouté avec succès
        '500':
          description: Erreur lors de l'ajout du message

  /message:
    get:
      summary: Obtenir les messages par ID de conversation
      tags: 
        - Message
      parameters:
        - in: query
          name: id_conv
          required: true
          schema:
            type: integer
          description: ID de la conversation
      responses:
        '200':
          description: Messages récupérés avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_msg:
                      type: integer
                    id_conv:
                      type: integer
                    dat_msg:
                      type: string
                      format: date-time
                    txt_msg:
                      type: string
                    id_sender:
                      type: integer
        '500':
          description: Erreur lors de la récupération des messages
