name: Deploy Backend

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SSH into EC2 and redeploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker stop express-backend
          sudo docker rm express-backend
          sudo docker rmi express-image
          cd /home/ubuntu/mspr && git pull
          cd /home/ubuntu/mspr && sudo docker build -t express-image express-backend/
          sudo docker run --name express-backend -d -p 3000:3000 express-image 
          node /home/ubuntu/mspr/express-backend/seeds/initialization.js
