name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd express-backend
          npm install && npm update

      - name: Run Jest
        run: |
          cd express-backend
          npx jest --config=jest.config.js

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into EC2 and redeploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/mspr/mspr && npm install && npm rebuild sqlite3
            sudo docker stop express-backend
            sudo docker rm express-backend
            sudo docker rmi express-image
            cd /home/ubuntu/mspr && git pull
            cd /home/ubuntu/mspr && sudo docker build -t express-image express-backend/
            sudo docker run --name express-backend -d -p 3000:3000 express-image
